environment: local
smtp-server: smtp.gmail.com
smtp-port: "587"
smtp-username: storitest0@gmail.com
smtp-password: "fjli pxvq fdwu hojr"
general-email: "storitest0@gmail.com"
db-host: localhost
db-port: "5432"
db-username: root
db-password: root
db-schema: pgdb